This line is adding in dev branch........
This line is updated....
This file is for practicing purpose. contains the db connection logic

updating this line for practicing merge concept in remote repo
thank u
